### PR TITLE
Idrice1

### PR DESCRIPTION
**Pull request by idrice24**

### CODE REVIEW

**Comment by idrice24** [comment]
bug please help me

**Comment by Ghislain1** [comment]
@idrice24  do you get any theory or link where i can read bout  **googlemap in angular?**

**Comment by Ghislain1** [comment]
Can you do another issue?   google map i have no idea  i must read too

**Comment by idrice24** [comment]
## this is a [link](https://developers.google.com/maps/gmp-get-started)

**Comment by Ghislain1** [comment]
https://angular-maps.com/guides/getting-started/

**Comment by Ghislain1** [comment]
@idrice24  sorry  do another issue first!! leave map

**Comment by idrice24** [comment]
ok

**Comment by Ghislain1** [comment]
@idrice24   PR build failde !! just delete it

**Pull request merged**
