### PR TITLE
Update config.yml issue #162

### PR DESCRIPTION
**Pull request by idrice24**

### CODE REVIEW

**Comment by Ghislain1** [comment]
https://stackoverflow.com/questions/63860001/angular-test-fails-to-run-with-chromeheadlessci-in-github-action

karma.conf.js

**Comment by idrice24** [comment]
please can you check 
to see what is the problem

**Comment by Ghislain1** [comment]
I testfail

**Comment by Ghislain1** [comment]
i send you a lin on comment here

**Comment by Ghislain1** [comment]
https://stackoverflow.com/questions/63860001/angular-test-fails-to-run-with-chromeheadlessci-in-github-action

**Comment by idrice24** [comment]
when i run npm run test i have this error

Cannot load browser "ChromeHeadlessCI": it is not registered! Perhaps you are missing some plugin?
i dont know where to check  this plugins

**Pull request closed without merging**
